/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NapiAudioContext {
  get currentTime(): number
  get sampleRate(): number
  get renderQuantumSize(): number
  get state(): string
  constructor()
  get baseLatency(): number
  get outputLatency(): number
  get sinkId(): string
}

export declare class NapiAudioDestinationNode {
  get numberOfInputs(): number
  get numberOfOutputs(): number
  connect(dest: NapiGainNode | NapiAudioDestinationNode | NapiAudioParam, output?: number | undefined | null, input?: number | undefined | null): void
  get maxChannelCount(): number
}

export declare class NapiAudioParam {
  get value(): number
  set value(value: number)
  setValueAtTime(value: number, time: number): void
  linearRampToValueAtTime(value: number, endTime: number): void
  exponentialRampToValueAtTime(value: number, endTime: number): void
  setValueCurveAtTime(values: Float32Array, startTime: number, duration: number): void
}

export declare class NapiGainNode {
  get numberOfInputs(): number
  get numberOfOutputs(): number
  connect(dest: NapiGainNode | NapiAudioDestinationNode | NapiAudioParam, output?: number | undefined | null, input?: number | undefined | null): void
  constructor(context: NapiAudioContext, _: object)
}

export declare class NapiOscillatorNode {
  get numberOfInputs(): number
  get numberOfOutputs(): number
  connect(dest: NapiGainNode | NapiAudioDestinationNode | NapiAudioParam, output?: number | undefined | null, input?: number | undefined | null): void
  constructor(context: NapiAudioContext, _: object)
}
